# Generated by Django 4.2.1 on 2023-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_file_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
