# Generated by Django 4.2.1 on 2023-06-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hystory',
            new_name='History',
        ),
    ]
