# Generated by Django 4.2.1 on 2023-06-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_first_name_books_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Product',
        ),
    ]
